// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvydgapqmdwgnmpebgdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2eWRnYXBxbWR3Z25tcGViZ2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mzg3OTIsImV4cCI6MjA3MTExNDc5Mn0.j5k9D_fwE7e5_kav1iNsGOf6hqMX-Pg3Voxl2wXxnnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});